#!/usr/bin/env python3
"""Regenerate the progress block in ROADMAP.md from its checkboxes.

A phase is any `## <Phase>: <title>` heading; its items are the `- [x]`, `- [~]` and `- [ ]` lines
under it. `[~]` (written, not verified) counts as half done. Overall progress is the mean of the
phase fractions, so a phase with no items yet counts as 0.

Usage: python3 roadmap_progress.py [path/to/ROADMAP.md]
"""
import re
import sys

START, END = "<!-- progress:start -->", "<!-- progress:end -->"
WIDTH = 20


def bar(frac):
    n = round(frac * WIDTH)
    return "`[" + "█" * n + "░" * (WIDTH - n) + "]`"


def phases(text):
    out, cur = [], None
    for line in text.splitlines():
        if line.startswith("## "):
            head = line[3:].strip()
            cur = [head.split(":")[0].strip(), 0, 0.0] if ":" in head else None
            if cur:
                out.append(cur)
        elif cur:
            m = re.match(r"\s*[-*] \[([ xX~])\]", line)
            if m:
                cur[1] += 1
                cur[2] += {"x": 1, "X": 1, "~": 0.5}.get(m.group(1), 0)
    return out


def render(ph):
    fracs = [done / items if items else 0.0 for _, items, done in ph]
    overall = sum(fracs) / len(fracs) if ph else 0.0
    unit = ph[0][0].split()[0].lower() if ph else "phase"
    head = f"**Progress: {overall:.0%} of the {len(ph)}-{unit} plan** {bar(overall)}"
    started = [(p[0], f) for p, f in zip(ph, fracs) if p[1]]
    if started:
        avg = sum(f for _, f in started) / len(started)
        span = started[0][0] if len(started) == 1 else f"{started[0][0]} to {started[-1][0]}"
        head += f" · {span} in progress: {avg:.0%} {bar(avg)}"
    rows = ["| Phase | Items | Done | Progress | |", "| :--- | ---: | ---: | :--- | ---: |"]
    for (name, items, done), f in zip(ph, fracs):
        if items:
            rows.append(f"| {name} | {items} | {done:g} | {bar(f)} | {f:.0%} |")
        else:
            rows.append(f"| {name} | - | - | {bar(0)} | not started |")
    note = "_Generated by `roadmap_progress.py` from the checkboxes below; rerun it after ticking items._"
    return [head, "", *rows, "", note]


def main(path="ROADMAP.md"):
    with open(path, encoding="utf-8", newline="") as f:
        text = f.read()
    if START not in text or END not in text:
        sys.exit(f"{path}: missing {START} / {END} markers")
    nl = "\r\n" if "\r\n" in text else "\n"
    ph = phases(text)
    before, rest = text.split(START, 1)
    after = rest.split(END, 1)[1]
    with open(path, "w", encoding="utf-8", newline="") as f:
        f.write(before + START + nl + nl.join(render(ph)) + nl + END + after)
    done = sum(d / i if i else 0 for _, i, d in ph) / len(ph) if ph else 0
    print(f"{path}: {done:.0%} across {len(ph)} phases")


if __name__ == "__main__":
    main(*sys.argv[1:2])
